# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  deployment:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    name: Scan the web application
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Observatory Github Action
        id: observatory
        uses: simonireilly/observatory-github-action@v0.1.0
        with:
          web_host: ${{ secrets.WEB_HOST }}
      # Use any comment plugin that you like, so long as it supports a string input
      - name: 'Save observatory report to file'
        run: echo "${{ steps.observatory.outputs.observatory-report }}" >> observatory.md
      - name: ZAP Scan
        id: zapScan
        uses: iib0011/action-baseline@v0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "owasp/zap2docker-stable"
          target: "https://www.zaproxy.org"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
    

      # # Example of using the output
      # - id: 'uploaded-files'
      #   uses: 'foo/bar@main'
      #   env:
      #     file: '${{ steps.upload-file.outputs.uploaded }}'
