# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  deployment:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    name: Scan the web application
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Observatory Github Action
        id: observatory
        uses: simonireilly/observatory-github-action@v0.1.0
        with:
          web_host: ${{ secrets.WEB_HOST }}
      # Use any comment plugin that you like, so long as it supports a string input
      - name: 'Save observatory report to file'
        run: echo "${{ steps.observatory.outputs.observatory-report }}" >> Observatory_report.md
      - name: Convert Observatory_report.md to PDF
      - uses: 3rdJCG/mdtopdf-action
        with:
          root_file: 'Observatory_report.md'
      - name: ZAP Scan
        if: always()
        id: zapScan
        uses: iib0011/action-baseline@v0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "owasp/zap2docker-stable"
          target: "https://www.zaproxy.org"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
      - name: 'Rename reports'
        run: mv report_html.html Zap_report.html

      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: OWASP Zap, Mozilla Observatory - Post-deployment report 
          # email body as text
          body: The post-deployment test was a ${{ job.status }}. Here are attached the Zap and Mozilla Observatory reports.
          attachments: Observatory_report.pdf,Zap_report.html
          # comma-separated string, send email to
          to: ${{secrets.RECIPIENTS}}
          # from email name
          from: Github
