# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test code Quality
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Set permissions 
        run: |
          sudo mkdir -p /home/runner/work/_temp/_github_home
          sudo chown -R 9901:9901 /home/runner/work/_temp/_github_home

          sudo mkdir -p /home/runner/work/$REPO_NAME
          sudo chown -R 9901:9901 /home/runner/work/$REPO_NAME
        env:
          REPO_NAME: ${{ github.event.repository.name }}
      - name: Run MobSF Analysis
        uses: fundacaocerti/mobsf-action@master
        env:
          INPUT_FILE_NAME: tiny.apk
          SCAN_TYPE: apk
          OUTPUT_FILE_NAME: mobsf-report
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Mobsf, Dependency check - Build report
          # email body as text
          body: The build has ${{ job.status }}ed. Here are attached the Mobsf and Dependency check reports.

          attachments: mobsf-report.pdf, reports/dependency-check-report.html
          # comma-separated string, send email to
          to: ibracool99@gmail.com
          # from email name
          from: Github
    #android
    