# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test code Quality
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set permissions 
        if: always()
        run: |
          sudo mkdir -p /home/runner/work/_temp/_github_home
          sudo chown -R 9901:9901 /home/runner/work/_temp/_github_home

          sudo mkdir -p /home/runner/work/$REPO_NAME
          sudo chown -R 9901:9901 /home/runner/work/$REPO_NAME
        env:
          REPO_NAME: ${{ github.event.repository.name }}
    
      - name: Run MobSF Analysis
        if: always()
        uses: fundacaocerti/mobsf-action@master
        env:
          INPUT_FILE_NAME: sms.apk
          SCAN_TYPE: apk
          OUTPUT_FILE_NAME: mobsf-report
      - name: create report.xlsx
        run: |
          chmod -R 755 .
      - name: Mobsf report to excel
        if: always()
        id: excel
        uses: iib0011/json2excel-action@main
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Mobsf - Build report
          # email body as text
          body: The build was a ${{ job.status }}. Here is attached the Mobsf check report.

          attachments: mobsf-report.pdf,mobsf-report.json,report.xlsx
          # comma-separated string, send email to
          to: ${{secrets.RECIPIENTS}}
          # from email name
          from: Github
    #android
    
